#SELECTS

#achar todos os contatos de todas as listas de contatos de um usuario
SELECT LDC.NOME, U.* FROM USUARIO DONO 
JOIN LISTA_DE_CONTATOS LDC ON DONO.USUARIO_ID = DONO
JOIN USUARIO U ON U.USUARIO_ID = LDC.USUARIO_ID
WHERE DONO.NOME = 'Alan';

#achar todos os compromissos de um usuario
SELECT C.*, R.* FROM USUARIO 
JOIN CALENDARIO USING(USUARIO_ID)
JOIN COMPROMISSO USING(COMPROMISSO_ID)
LEFT JOIN REUNIAO USING(REUNIAO_ID)
WHERE USUARIO_ID = 1;