DROP TABLE IF EXISTS LISTA_DE_CONTATOS

CREATE TABLE LISTA_DE_CONTATOS (
	LISTA_DE_CONTATOS_ID NUMERIC PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DONO NUMERIC NOT NULL,
	USUARIO_ID NUMERIC,
	
	FOREIGN KEY (DONO) REFERENCES USUARIO(USUARIO_ID),
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE USUARIO (
	USUARIO_ID NUMERIC PRIMARY KEY,
	

);

CREATE TABLE USUARIO_PREMIUM (
	USUARIO_PREMIUM_ID NUMERIC PRIMARY KEY,
	DATA_DE_TERMINO DATE NOT NULL,
	ULTIMO_PAGAMENTO DATE NOT NULL,
	METODO_DE_PAGAMENTO CHAR(20) NOT NULL,
	
	FOREIGN KEY METODO_DE_PAGAMENTO REFERENCES METODO_DE_PAGAMENTO(NOME)
);

CREATE TABLE METODO_DE_PAGAMENTO (
	NOME NUMERIC PRIMARY KEY,
	DESCRICAO VARCHAR(255)
);

CREATE TABLE CALENDARIO (
	CALENDARIO_ID NUMERIC PRIMARY KEY,
	COMPROMISSO_ID NUMERIC
	
);

CREATE TABLE COMPROMISSO (

);

CREATE TABLE REUNIAO (

);
