ALTER TABLE COMPROMISSO DROP FOREIGN KEY FK_REUNIAO;
DROP VIEW IF EXISTS COMPROMISSO_REUNIAO;
DROP TABLE IF EXISTS REUNIAO;
DROP TABLE IF EXISTS LISTA_DE_CONTATOS;
DROP TABLE IF EXISTS CALENDARIO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS USUARIO_PREMIUM;
DROP TABLE IF EXISTS METODO_DE_PAGAMENTO;
DROP TABLE IF EXISTS COMPROMISSO;
DROP TABLE IF EXISTS SALA_DE_REUNIAO;

CREATE TABLE METODO_DE_PAGAMENTO (
	NOME CHAR(20) PRIMARY KEY,
	DESCRICAO VARCHAR(255)
);

CREATE TABLE SALA_DE_REUNIAO (
	NOME VARCHAR(100) PRIMARY KEY
);

CREATE TABLE COMPROMISSO (
	COMPROMISSO_ID NUMERIC PRIMARY KEY,
	DATA_DE_INICIO TIMESTAMP NOT NULL,
	DATA_DE_TERMINO TIMESTAMP NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIO_PREMIUM (
	USUARIO_PREMIUM_ID NUMERIC PRIMARY KEY,
	DATA_DE_TERMINO TIMESTAMP NOT NULL,
	ULTIMO_PAGAMENTO TIMESTAMP NOT NULL,
	METODO_DE_PAGAMENTO CHAR(20) NOT NULL,
	
	FOREIGN KEY (METODO_DE_PAGAMENTO) REFERENCES METODO_DE_PAGAMENTO(NOME)
);

CREATE TABLE USUARIO (
	USUARIO_ID NUMERIC PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	TELEFONE NUMERIC,
	USUARIO_PREMIUM_ID NUMERIC,
	
	FOREIGN KEY (USUARIO_PREMIUM_ID) REFERENCES USUARIO_PREMIUM(USUARIO_PREMIUM_ID)
);

CREATE TABLE LISTA_DE_CONTATOS (
	LISTA_DE_CONTATOS_ID NUMERIC,
	NOME VARCHAR(100) NOT NULL,
	DONO NUMERIC NOT NULL,
	USUARIO_ID NUMERIC,
	
	PRIMARY KEY (LISTA_DE_CONTATOS_ID, USUARIO_ID),
	FOREIGN KEY (DONO) REFERENCES USUARIO(USUARIO_ID),
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE CALENDARIO (
	USUARIO_ID NUMERIC,
	COMPROMISSO_ID NUMERIC,
	
	PRIMARY KEY (USUARIO_ID, COMPROMISSO_ID),
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
	FOREIGN KEY (COMPROMISSO_ID) REFERENCES COMPROMISSO(COMPROMISSO_ID)
);

CREATE TABLE REUNIAO (
	REUNIAO_ID NUMERIC,
	NOME VARCHAR(100) NOT NULL,
	SALA_DE_REUNIAO VARCHAR(100) NOT NULL,
	USUARIO_ID NUMERIC NOT NULL,
	
	PRIMARY KEY(REUNIAO_ID, USUARIO_ID),
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
	FOREIGN KEY (SALA_DE_REUNIAO) REFERENCES SALA_DE_REUNIAO(NOME)
);

ALTER TABLE COMPROMISSO
ADD COLUMN REUNIAO_ID NUMERIC AFTER DESCRICAO,
ADD CONSTRAINT FK_REUNIAO FOREIGN KEY (REUNIAO_ID) REFERENCES REUNIAO(REUNIAO_ID);

CREATE VIEW COMPROMISSO_REUNIAO AS SELECT * FROM COMPROMISSO JOIN REUNIAO USING(REUNIAO_ID);
