#achar todos os contatos de todas as listas de contatos de um usuario COM VIEW
SELECT DISTINCT LDC.NOME, U.* FROM USUARIO_SIMPLES DONO 
JOIN LISTA_DE_CONTATOS LDC ON DONO.USUARIO_ID = DONO
JOIN USUARIO_SIMPLES U ON U.USUARIO_ID = LDC.USUARIO_ID
WHERE DONO.USUARIO_ID = 1
ORDER BY LDC.NOME;

#achar todas as mensagens de um chat e quem as mandou
SELECT U.NOME, CONTEUDO, A.*, DATA_DE_ENVIO FROM MENSAGEM M
JOIN CHAT C ON C.CHAT_ID = M.CHAT_ID
JOIN USUARIO U ON M.USUARIO_ID = U.USUARIO_ID
LEFT JOIN ARQUIVO A USING (ARQUIVO_ID)
WHERE C.CHAT_ID = 2
AND M.USUARIO_ID = C.USUARIO_ID
ORDER BY DATA_DE_ENVIO;

#olhar o calendario do usuario 1
SELECT U.NOME, C.* FROM USUARIO U
JOIN CALENDARIO CAL USING(USUARIO_ID)
JOIN COMPROMISSO_REUNIAO C USING(COMPROMISSO_ID)
WHERE U.USUARIO_ID = 1;

#Todas as chamadas do usuario 1
SELECT U.*, CH.* FROM USUARIO_SIMPLES U
JOIN CHAT C ON C.USUARIO_ID = U.USUARIO_ID
JOIN CHAMADA CH ON C.CHAT_ID = CH.CHAT_ID
WHERE U.USUARIO_ID = 1;

#Todos os arquivos enviados pelo usuario 1
SELECT U.*, A.* FROM USUARIO_SIMPLES U
JOIN MENSAGEM M USING(USUARIO_ID)
JOIN ARQUIVO A USING(ARQUIVO_ID)
WHERE USUARIO_ID = 1;

#Usuarios que tem mais de um compromisso
select * from usuario_simples
join calendario using(usuario_id)
join compromisso using(compromisso_id)
group by usuario_id
having count(compromisso_id) > 1;

#B1
#achar todos os chats de um usuario X
SELECT DISTINCT CHAT_ID, U.NOME AS PARTICIPANTE FROM CHAT 
JOIN USUARIO U USING(USUARIO_ID)
WHERE U.NOME <> 1
AND CHAT_ID IN (SELECT DISTINCT CHAT_ID FROM CHAT 
WHERE USUARIO_ID = 1)
ORDER BY CHAT_ID;

#A1
SELECT DISTINCT U.USUARIO_ID, U.NOME, COUNT(C.COMPROMISSO_ID) FROM USUARIO DONO 
JOIN LISTA_DE_CONTATOS LDC ON DONO.USUARIO_ID = DONO
JOIN USUARIO U ON U.USUARIO_ID = LDC.USUARIO_ID
LEFT JOIN CALENDARIO C ON C.USUARIO_ID = U.USUARIO_ID
WHERE DONO.USUARIO_ID = 1
GROUP BY U.USUARIO_ID;

#C
#TODOS OS USUARIOS QUE NAO TEM CHAT COM O USUARIO 2 E SEUS METODOS DE PAGAMENTO
SELECT DISTINCT U1.USUARIO_ID, NOME, UP.METODO_DE_PAGAMENTO FROM USUARIO U1 
LEFT JOIN USUARIO_PREMIUM UP ON U1.USUARIO_PREMIUM_ID = UP.USUARIO_PREMIUM_ID
WHERE NOT EXISTS (SELECT * FROM CHAT 
WHERE USUARIO_ID = U1.USUARIO_ID
AND CHAT_ID IN (SELECT DISTINCT CHAT_ID FROM CHAT
JOIN USUARIO USING(USUARIO_ID)
WHERE USUARIO_ID = 2))
