CREATE TRIGGER ATUALIZA_CALENDARIO AFTER INSERT
ON COMPROMISSO
FOR EACH ROW
	INSERT INTO CALENDARIO (USUARIO_ID, COMPROMISSO_ID)
	SELECT DISTINCT R.USUARIO_ID, C.COMPROMISSO_ID FROM REUNIAO R JOIN COMPROMISSO C USING(REUNIAO_ID) WHERE COMPROMISSO_ID = NEW.COMPROMISSO_ID;

#TRIGGER TEST
CREATE TRIGGER ADD_LISTA_DE_CONTATOS BEFORE INSERT
ON LISTA_DE_CONTATOS
BEGIN 
	IF OLD.LISTA_DE_CONTATOS_ID IN (SELECT DISTINCT LISTA_DE_CONTATOS_ID FROM LISTA_DE_CONTATOS) THEN
		NEW.NOME = (SELECT DISTINCT NOME FROM LISTA_DE_CONTATOS WHERE LISTA_DE_CONTATOS_ID = OLD.LISTA_DE_CONTATOS_ID)
		NEW.DONO = (SELECT DISTINCT DONO FROM LISTA_DE_CONTATOS WHERE LISTA_DE_CONTATOS_ID = OLD.LISTA_DE_CONTATOS_ID)
END;
